### ISSUE TITLE
BroadcastGroup according to room name/id

### ISSUE THREAD

**Issue by jkbstrmen** [y-crdt/yrs-warp#15]
Hi,

is there a way how to get an already open BroadcastGroup  by room name or create new BroadcastGroup if not yet open for room at runtime? I tried to provide Arc<Mutex<SomeKindOfContextHolder>> for warp filter, but I cannot create new BroadcastGroup and add it to context, in ws_handler because BroadcastGroup::new() is async.

I was thinking about something like this (pseudocode):
```
async fn ws_handler(room_id: String, ws: Ws, context: Arc<Mutex<SomeKindOfContext>>) -> Result<impl Reply, Rejection> {
    let context_locked = context.lock().unwrap();
    let room_broadcast = context_locked.get_broadcast_for_room_if(room_id);
    let bcast;
    if let Some(broadcast) = room_broadcast {
        bcast = broadcast;
    } else {
        bcast = create_broadcast(context_locked, room_id);
    }
    Ok(ws.on_upgrade(move |socket| peer(socket, bcast)))
}
```

Thanks for any suggestions.

**Comment by Horusiath** [comment]
Wouldn't something like that work?

```rust
let rooms = Arc::new(Mutex::new(HashMap::new()));

// create or return room
let room = {
    let mut rooms = rooms.lock().await;
    match rooms.entry(room_id) {
        Entry::Vacant(e) => {
            // establish a new broadcast group
            let awareness = Arc::new(RwLock::new(Awareness::default()));
            let group = Arc::new(BroadcastGroup::new(awareness, BUFFER_CAP).await);
            e.insert(group).clone()
        }
        Entry::Occupied(e) => e.get().clone(), // return existing broadcast group
    }
};
```

**Comment by jkbstrmen** [comment]
Thanks for your answer. That is exactly what I was trying to do. My problem was usage of **std::sync::Mutex** instead of **tokio::sync::Mutex** there, which was throwing compile time error _future cannot be sent between threads safely_. 

Great work here by the way. Thanks for that as well.
